<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_employee</name>
   <tag></tag>
   <elementGuidId>aff30346-2b47-469e-b120-b1ebb408aa1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>00f18d21-16db-4c1c-8287-0a12a93eeeb1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
